### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by Holmes-GU** [yzfly/SimpleTreeHeight#2]
Hi, I am a phd candidate and I saw you running source code of paper 'YOWO'. Have you reproduced the results in Table 2?

**Comment by yzfly** [comment]
My results are slightly worse. Let's discuss this issue in yowo's issue area.

**Comment by Holmes-GU** [comment]
And have read the source Code of the paper? I really do not understand the clause 'if seen ,12800' in region_loss.py? Do you know its function?

**Comment by yzfly** [comment]
Sorry, I don't know. Maybe you can ask the author for some help?
