### ISSUE TITLE
JHMDB-21 training gt

### ISSUE THREAD

**Issue by Holmes-GU** [yzfly/SimpleTreeHeight#3]
Hi, 
I am a student from SJTU. Would you like to share JHMDB-21 training gt? Thank you very much

Zhihao Gu

**Comment by yzfly** [comment]
Hi, 
I'm also a student, I’m from UESTC. Actually，I have shared it. Please reference to [issues25](https://github.com/wei-tim/YOWO/issues/25) 

![image](https://user-images.githubusercontent.com/46625232/89834378-50c63b00-db95-11ea-9b31-4cf88ef6c405.png)

Please note that this is generated by myself, accuracy cannot be guaranteed. If you can't download it, tell me your email and I'll try to give you a copy.

I use it and get similar results as YOWO. If you can't reproduce the results, please select your hyperparameter carefully. With some improvements, I got better results than YOWO on both jhmdb21 and ucf24.

**Comment by Holmes-GU** [comment]
Ok, my mail is gzhmsy@126.com，one more question, when you evaluate video-map on ucf and  jhmdb, where do you find the testlist-video files? I failed to find them.
Yours


| |
SJTU 顾智浩
邮箱：gzhmsy@126.com
|

签名由 网易邮箱大师 定制

On 08/11/2020 05:57, yzfly wrote:

Hi,
I'm also a student, I’m from UESTC. Actually，I have shared it. Please reference to issues25

Please note that this is generated by myself, accuracy cannot be guaranteed. If you can't download it, tell me your email and I'll try to give you a copy.

I use it and get similar results as YOWO. If you can't reproduce the results, please select your hyperparameter carefully. With some improvements, I got better results than YOWO on both jhmdb21 and ucf24.

**Comment by r09921135** [comment]
@yzfly Hi! 
Would you mind to share the hyperparameters you choose or what kinds of improvements you made? 
I've been struggling to reproduce the results... very looking forward to your respond! Thank you very much!

**Comment by yzfly** [comment]
It's been too long to remember. Maybe you can refer to our paper https://openaccess.thecvf.com/content/ACCV2020W/MMHAU/html/Liu_Real-time_spatio-temporal_action_localization_via_learning_motion_representation_ACCVW_2020_paper.html
